### PR TITLE
check this port for discovery

### PR DESCRIPTION
**Pull request by dogualpay**

### CODE REVIEW

**Comment by alejoseb** [comment]
Hi,
Thanks for the example. It has some issues: 
- Modbus library must be linked not copied into the example
- There is a ".vs" folder that is on the root of your commit, that must be deleted and not part of the commit at all.
- The name of the example folder must include the name of the board DISC1 to differentiate from the example that is already there.
- The example should be meaningful and do something more than just initializing the Modbus library. Check the other examples.
- Update the README file accordingly including a short description there about the new example

**Comment by ozdemirmcihad** [comment]
Hello; I really appreciate these codes. I imported your code for F446 and it actually works. I can read the data I wrote from ModbusPol, but I cannot write data from F4 to modbuspol. What should I do to write data?

**Comment by alejoseb** [comment]
closing since no answer to solve this pull request

**Comment by ozdemirmcihad** [comment]
Hello; Does the library support multiusart use

**Comment by alejoseb** [comment]
hi @ozdemirmcihad  please open an issue to discuss your questions. This thread is a pull-request, which is not used for asking questions, also this thread is already closed.

**Pull request closed without merging**
